[package]
name = "new-project"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.12"
redis = { version = "0.27.6", features = ["aio"] }
tokio = { version = "1", features = ["full"] }
